### ISSUE TITLE
Normal Search

### ISSUE THREAD

**Issue by jinsun-yoo** [swsnu/swpp2019-team2#112]
1. Edge에서
2. admin/admin로그인한 다음에 
3. 왼쪽에 있는 모든 박스를 다 체크해도 /혹은 하나만 체크해도 아무것도 뜨지 않습니다 ㅜㅜ 립 베이스 모두 그렇습니다..

**Comment by HaeSe0ng** [comment]
search 버튼 클릭하면 뜨는 거 같아요

**Comment by jinsun-yoo** [comment]
앗 그게 Search 버튼이라는게 조금 명확해야할거같아요! 저는 처음볼때 그냥 메뉴 제목(?)같은건줄 알았어요 ㅠㅠ

**Comment by aeri206** [comment]
#131 Done
- Search UI 수정
