### ISSUE TITLE
Request(minor) search 버튼이 잘 보이지 않습니다!

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team2#113]
<img width="1440" alt="Screen Shot 2019-12-05 at 6 51 02 PM" src="https://user-images.githubusercontent.com/13305988/70224218-3fb86500-1790-11ea-89c0-4a3838244260.png">

search 버튼이 흰색이고, hover 시 cursor 변화도 없어서 버튼이 있는지 잘 보이지 않습니다ㅠ

**Comment by das425** [comment]
수정하겠습니다!

**Comment by aeri206** [comment]
#131 
Done
