### ISSUE TITLE
Budget search 화면 공백

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team2#116]
<img width="1440" alt="Screen Shot 2019-12-05 at 6 52 45 PM" src="https://user-images.githubusercontent.com/13305988/70224381-827a3d00-1790-11ea-8c98-ce22c5172d59.png">

budget search 화면으로 들어가면 이런 화면이 뜨는데요! 화면이 전체적으로 아래쪽으로 쭉 밀려 있어서 보기가 어렵습니다ㅠㅠ 
(search-tag를 제외한 모든 화면에서 이 현상이 발생하네요! 스타일링 통일이 덜 된 것일수도 있겠네요)

**Comment by das425** [comment]
넵 아직 스타일링 중이라..ㅎㅎ

**Comment by haesookim** [comment]
화이팅입니당.....!ㅎㅎㅎㅎ💪💪💪

**Comment by aeri206** [comment]
#134 Done
Header CSS 수정
