### ISSUE TITLE
Login이 안된 상태에서 Budget Search 클릭

### ISSUE THREAD

**Issue by dreamsh19** [swsnu/swpp2019-team2#117]
로그인이 안된 상태에서 상단 배너의 Budget Search를 클릭하면
로그인을 요구하는 페이지가 나오지 않고
로그인이 된 것 같은 상태의 페이지가 나옵니다
(Log-out  / My Page ) 등 존재

**Comment by das425** [comment]
넵 지금 버젯서치랑 서치랑은 로그인이 필요없어서 그렇습니다ㅠㅠ!

**Comment by aeri206** [comment]
Done
헤더 수정
