### ISSUE TITLE
[bug report] sale page UI

### ISSUE THREAD

**Issue by ttoru96** [swsnu/swpp2019-team2#120]
환경: 
OS: mac sierra
브라우저: chrome

모든 페이지(아래 예시는 sale page)로 들어갔을 때 위에는 blank space 이고 아래로 스크롤 해야지만 캘린더가 보입니다. 이와 같은 UI가 의도된 바가 아니라면 유저빌리티를 위해 수정이 필요할 것으로 보입니다. 
<img width="1359" alt="Screen Shot 2019-12-05 at 6 53 20 PM" src="https://user-images.githubusercontent.com/44546247/70224545-c8370580-1790-11ea-9989-e34bad613543.png">

**Comment by njsh4261** [comment]
OS: Linux Mint
브라우저: Chrome
같은 문제 겪었습니다

**Comment by aeri206** [comment]
css를 적용하는 과정에서 header의 높이가 잘못설정되는 문제가 있었습니다 감사합니다! #130
