### ISSUE TITLE
Mypage에서의 dom 겹침 현상

### ISSUE THREAD

**Issue by haesookim** [swsnu/swpp2019-team2#121]
<img width="1440" alt="Screen Shot 2019-12-05 at 6 55 52 PM" src="https://user-images.githubusercontent.com/13305988/70224631-f4528680-1790-11ea-84a7-db30ebe964d0.png">

content DOM이 올라와서 navbar를 가리네요! #119 도 이런 문제일수도 있겠다는 생각이 들어요..!

**Comment by das425** [comment]
넵 감사합니다!!

**Comment by aeri206** [comment]
#134 Done
- Mypage UI 수정
