### ISSUE TITLE
Search, My page 관련 버그

### ISSUE THREAD

**Issue by 1207koo** [swsnu/swpp2019-team2#123]
Search 창에서 Lip Base Cheek을 고르지 않는 한 화면이 안 내려가는 것이 불편함
또한 저 3개도 화면 밑에 가려져 있어서 유저 입장에서 알기 힘듦
그리고 검색이 결과가 안 뜸

My Page에서 Log out 말고는 나갈 버튼이 없음.
선호 색상, 선호 베이스 등이 선택하지 않았을 때 그냥 빈 문자열만 나와서 알기 힘듦
선호 브랜드가 공백 없이 붙여서 추가되어서 가독성이 떨어짐

탑 바(?)가 사이트마다 달라서 헷갈림

**Comment by das425** [comment]
네 ㅠㅠ 아직 스타일링이 덜 되어서 그런 것 같습니다! 감사합니다

**Comment by aeri206** [comment]
감사합니다!
#134 Done
- Mypage UI 수정
- Header 통일
- 좌측 서치바 기본 설정 및 floating 설정 완료
