### ISSUE TITLE
[bug report] my page에서 고친게 적용이 안되요

### ISSUE THREAD

**Issue by vionicbest** [swsnu/swpp2019-team2#124]
admin/ admin으로 로그인했을 때
![image](https://user-images.githubusercontent.com/38846024/70224801-3aa7e580-1791-11ea-9e7c-a8d2edf4236f.png)

**Comment by das425** [comment]
앗 알려주셔서 감사합니다 확인해보겠습니다!

**Comment by aeri206** [comment]
#129 Done
