### ISSUE TITLE
발견한 문제들

### ISSUE THREAD

**Issue by peterhyun** [swsnu/swpp2019-team2#126]
1. 맥북 사용중인데(Pro 13인치) 화면을 반띵하면 Header의 Budget Search, Tone Analysis가 쪼개집니다...

2. My page도 반띵하면  화면이 가려집니다.

3. 
<img width="1419" alt="Screen Shot 2019-12-05 at 6 56 35 PM" src="https://user-images.githubusercontent.com/22678965/70224916-675bfd00-1791-11ea-8506-b270111920cb.png">

**Comment by das425** [comment]
헉 확인해보겠습니다ㅠ 감사합니다!!

**Comment by aeri206** [comment]
#134 
Done
CSS 수정
