### ISSUE TITLE
Naming and Styling

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team2#24]
코드 보는중에 해야할일이 생겨나서 이슈 남깁니다..!
코드 짜느라 바쁘겠지만 Naming이랑 Styling해주세요 😢 

1. eslint에 babel-eslint 적용
- eslint를 돌려보면 `state = { ... }` 와 같은 부분에서 `error Parsing error: Unexpected token = ` 와 같은 에러가 납니다! ES6~7 에서 바뀐 문법때문이라고 하는데 어짜피 Travis CI에서 eslint 검사해야하니깐 추가하는게 좋을 것 같습니다
참고 
- https://stackoverflow.com/questions/36001552/eslint-parsing-error-unexpected-token
- https://www.npmjs.com/package/babel-eslint
- **push 하기전에 `./node_modules/.bin/esint --fix src` 실행해주세요**

2. 변수 naming 
- [repo에서 td 검색결과](https://github.com/swsnu/swpp2019-team2/search?p=2&q=td&unscoped_q=td)
- td는 practice todolist의 잔재..로 우리 프로젝트랑은 전혀 관련이 없습니다ㅠㅠ
- 관련있는 이름으로 고치는게 좋을것 같습니다
- [eslint-airbnb naming convention](https://github.com/tipjs/javascript-style-guide#%EB%AA%85%EB%AA%85%EA%B7%9C%EC%B9%99naming-conventions)
- [Python Naming Convention - 한글](https://spoqa.github.io/2012/08/03/about-python-coding-convention.html)
- [Python Naming Convention - 영문](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html)

**Comment by das425** [comment]
네! 내일 고치고 이슈 올리도록 하겠습니다 :) 알려주셔서 감사합니다

**Comment by xixili3** [comment]
감사합니당 :)

**Comment by aeri206** [comment]
#35 td -> cosmos 변경완료
 - Reducer 추가 할 경우 추가 수정 필요
