### ISSUE TITLE
[dev/master]sales Info & Big Calendar test

### ISSUE THREAD

**Issue by das425** [swsnu/swpp2019-team2#36]
1. salesinfo 페이지는 버튼 추가 등 변경사항 있어서 제가 test code 전부 다시 짰습니다 :) 커버리지 90 넘어요!
2.  Big Calendar 페이지 test 커버리지가 75?퍼센트?이던데 이건 윤기가 혹시 고쳐줄 수 있나용

**Comment by lllY2Klll** [comment]
Big calendar page 테스트 해보겠습니다!

**Comment by lllY2Klll** [comment]
2번  BigCalendar.js test 추가 및 coverage 100만들어서 dev/master에 push 완료했습니다..!
