### ISSUE TITLE
Connected Router -> Browser Router 변경

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team2#37]
Login, Search Tag Reducer 등이 정상 작동 하지않음
- 원인?
- 해결 방안
  - 현재 push 된 dev/master의 코드를 전부 변경

**Comment by aeri206** [comment]
@xixili3 다된거면 close 해주세영

**Comment by xixili3** [comment]
Connectedrouter -> Browserrouter 변경완료했습니다.
