### ISSUE TITLE
ESLint 수정사항

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team2#41]
ESLint Rule configuration 추가 
```
  "no-underscore-dangle":0, #GetUsers_와 같은 method명 때문
  "import/prefer-default-export":0, #Default Export 제외 - 수정하려고 했으나 Import까지 다 손봐야 해서..
  "react/prop-types":0, # props-type-checking 무시
  "react/destructuring-assignment":[1, "always", { "ignoreClassFields": true }]
```

Autofix되는 부분말고 React 관련해서 ESLint에서 문제가 많이 생겼던 부분입니다 :)

참고부탁드려요..!

- [Destructing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md)  : 현재 Warning으로 처리함
    - [MDN Docs(Destructing)](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
- [No Props Spreading](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md)  - off
- [Button Type]( https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md) - type 추가해야함
- [변수 Naming - CamelCase](https://eslint.org/docs/rules/camelcase) - 변수명은 CamelCase로 작성해주세요..!
- [Test no-unused-ver](https://eslint.org/docs/rules/no-unused-vars) 
  다음과 같은 테스트코드에서 에러가 발생합니다. 일단 파일마다 disable 설정은 해놨는데 테스트 코드 다시 짜주세요 😢 
```
const spyGetUsers = jest
      .spyOn(actionCreators, 'getUsers')
      .mockImplementation(() => (dispatch) => {});
```
  - 테스트코드 Linter 설정하면서 봤는데
  ` const newInstance = component.find(SkinTone.WrappedComponent).instance(); `  이거는 그냥 코드 커버리지 용인가요..?

**Comment by aeri206** [comment]
수정 가능한 부분은 수정 후  이슈 남겼고, 수정해야할..것 같은 부분은 Warning으로 바꿨습니다 :) 확인후 수정 부탁드려요

**Comment by xixili3** [comment]
CamelCase 는 더욱 신경쓰도록 하겠습니다.
no-unused-ver 관련해서도 테스트 코드 짤때 더욱 신경쓰겠습니다.

감사합니다.
