### ISSUE TITLE
[ESLint] img 태그 error

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team2#42]
Back button으로 화살표를 삽입하는 경우
`<img src={arrow} alt="Back to Main" id="back-to-menu-button" onClick={() => this.menuHandler()} />` 의 코드에서 다음과 같은 에러가 발생합니다.
warning으로 해놓았는데 공통으로 들어가는 코드라 html구조를 바꿔서 수정하면 좋을것 같습니다..!

error  Non-interactive elements should not be assigned mouse or keyboard event listeners               jsx-a11y/no-noninteractive-element-interactions

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-interactions.md

**Comment by das425** [comment]
해결했습니다 :)
