### ISSUE TITLE
[ESLint] HTML - Label

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team2#43]
html 코드 중에서 
label 관련 부분에서 ESLint에러가 뜹니다

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md

**Comment by aeri206** [comment]
@xixili3 해결했나여

**Comment by xixili3** [comment]
넵 Label 관련 부분 신경써서 진행하겠습니다
