### ISSUE TITLE
React Parameter / State Update

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team2#44]
```
case actionTypes.PUT_USER:
      const userstatus = state.Users.map((User) => {
        if (User.id === action.targetID) {
          User.logged_in = action.logged_in;
          return User;
        }
        return User;
      });
```
위의 코드에서 
  17:11  error  Assignment to property of function parameter 'User'  no-param-reassign
에러가 발생합니다

- 관련 문서
https://eslint.org/docs/rules/no-param-reassign

- 해결방법
  - Spread 연산자 사용해서 해결가능합니다
  - [MDN Docs](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
  - https://codeburst.io/a-simple-guide-to-destructuring-and-es6-spread-operator-e02212af5831
```
case actionTypes.PUT_USER:
      const userstatus = state.Users.map((User) => {
        if (User.id === action.targetID) {
          const tmpUser = { ...User, logged_in: action.logged_in }; // create tmp user object
          return tmpUser;
        }
        return User;
      });```

**Comment by aeri206** [comment]
@xixili3 해결됐나용

**Comment by xixili3** [comment]
장고와 연동하면서 putUser 액션은 삭제되었습니다~ 감사합니다
