### ISSUE TITLE
sonar-project.properties

### ISSUE THREAD

**Issue by lllY2Klll** [swsnu/swpp2019-team2#48]
브랜치를 머지하는 과정에서 
소나클라우드 체크를 계속 통과하지 못하는 문제가 있었는데
소나클라우드는 자체적으로 테스트를 실행해서 coverage report를 만들지 못하고
먼저 생성된 report를 import 한다고 하네요..!
[SonarQube docs](https://docs.sonarqube.org/latest/analysis/coverage/) 참고바랍니다.

우선은 javascript 테스트를 위해 sonar-project.properties 파일에
`sonar.javascript.lcov.reportPaths=coverage/lcov.info` 를 추가했는데

나중에 장고 테스트를 하면 python  테스트를 위해 
`sonar.python.coverage.reportPaths=coverage.xml` 를 추가해야 할 것 같습니다.

장고 테스트 파일 생성 후 확인 바랍니다!

**Comment by aeri206** [comment]
장고 합친김에 파이썬도 추가할께요 💻

**Comment by aeri206** [comment]
현재 python(back) / node.js(front) 나눠져있는 travis test 하나로 합치고 sonarcloud에 파이썬 추가하겠습니다 :)
참고 - https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
  - python = 3.7일떄 ubuntu 14.04 (dist:trusty)를 지원하지 않는다고 해서 ubuntu 16.04(dist:xenial) 로 변경
[Xenial Build Environment](https://docs.travis-ci.com/user/reference/xenial/)
