### ISSUE TITLE
problem regarding back to main page button 

### ISSUE THREAD

**Issue by lllY2Klll** [swsnu/swpp2019-team2#50]
현재 뒤로가기 버튼(각 페이지의 화살표 버튼)이 input태그로 구현이 되어있습니다.

아마도 button 태그의 이미지를 변경하는 것이 쉽지 않기 때문일텐데

태그 타입을 input으로 했다보니 eslint checker는 onClick을 쓰지 말고 onChange를 쓰라고 했었어서 

onChange로 변경하고 나니 클릭했을 때 함수를 호출하지 못하는 문제가 생겼습니다. 

그래서 우선 dev/master에 다시 뒤로가기 버튼의 attribute를 onChange에서 onClick으로 바꾸어놓았는데

앞으로도 이런 방식을 채택할지 혹은 버튼 태그타입을 스타일링 할 수 있는지 알아봐야 할 것 같습니다..!

**Comment by aeri206** [comment]
[input type="button" vs button](https://m.blog.naver.com/PostView.nhn?blogId=lsj593&logNo=120204015398&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

지금 코드가 `input type="img"` 라고 되어있는데 뒤로가기 버튼이 입력값을 받는건 아니고 버튼의 역할만 하는거니깐 <button></button>으로 바꾸는게 좋을것 같습니다

++ [how to add background img to button tag](https://stackoverflow.com/questions/15461317/button-background-image)

**Comment by das425** [comment]
<button> 으로 설정한 뒤에 css로 background 설정 해보았으나 작동하지 않아서,
<button> <img> </button> 형식으로 버튼 안에 이미지를 넣는 방식으로 고쳤습니다.
dev/newLogin 브랜치에 고친 파일 적용하였습니다 :)

**Comment by xixili3** [comment]
dev/newLogin 확인결과 정상작동합니다
