### ISSUE TITLE
Cosmos 프로젝트 clone 후 사용 메뉴얼

### ISSUE THREAD

**Issue by xixili3** [swsnu/swpp2019-team2#52]
모두 고생많으십니다.
프로젝트 repo에서 클론 -> 수정 후 정상 동작 여부 테스트를 진행하실텐데 관련 메뉴얼을 올려드리겠습니다. 현재까지는 본 메뉴얼대로 진행하면 정상적으로 동작이 됩니다.

1.  Git 에서 프로젝트 clone( git clone {플젝 repo url} )

2.  프로젝트폴더/backend/ 로 들어가셔서 pip install -r requirements.txt  (패키지 종속성 관리)

3.  프로젝트폴더/backend/ 에서 python manage.py makemigrations 및 python manage.py migrate

4.  장고서버 실행 -> python manage.py runserver

5.  프로젝트폴더/frontend/ 에서 yarn install

6.  프로젝트폴더/frontend/ 에서 yarn start

7.  Cosmos 정상 작동여부 확인

프로젝트가 진행되면서 수정사항이 생길 수 있고, 수정사항이 생기면 이슈에 그때 그때 올리도록 하겠습니다.

모두들 좋은 하루 되세요~

**Comment by aeri206** [comment]
README에 실행방법 올려주세요 @xixili3

**Comment by xixili3** [comment]
README.md 업데이트 완료했습니다.
