### ISSUE TITLE
crawling BE & 구현된 FE 연결

### ISSUE THREAD

**Issue by aeri206** [swsnu/swpp2019-team2#58]
크롤링 Scrapy - BE (Django) 연결
BE (Django) - FE (React) 연결

**Comment by aeri206** [comment]
장고 모델 통합

**Comment by aeri206** [comment]
크롤링 - 컬러 옵션 추가 -> DB 필드 추가

**Comment by aeri206** [comment]
BE 수정에 따른 FE 대응

**Comment by xixili3** [comment]
FE 액션 리듀서 -> BE 장고 DB 호환
BE 장고 모델 -> FE 데이터 response

**Comment by xixili3** [comment]
FE 액션 리듀서 -> BE 장고 DB 호환
BE 장고 모델 -> FE 데이터 response

**Comment by aeri206** [comment]
> BE 장고 모델 -> FE 데이터 response

요거가 REST API..?

**Comment by xixili3** [comment]
네 맞습니다. 그걸로 해야 백에서 프론트로 데이터를 전송할수있거등요

**Comment by xixili3** [comment]
그거는 rest framework 모듈이 알아서 해줄테니 저희는 프론트에서 정확한 url에 정확한 axios만 보내면 됩니다.

**Comment by xixili3** [comment]
2019.11.07     FE, BE 연동 로드맵 (Aeri Cho, Sangmock Lee)

* 기존의 과제처럼 BE에서 데이터 전체를 가져와서 FE에서 핸들링 하는 것은 효율적이지 못하고 FE/BE를 나누어 프로젝트를 진행하는 의미가 사라집니다. 또한 크롤링을 진행하여 BE DB에 저장한 데이터들을 단순히 FE로 보내기만 하는 동작만을 구현하면 크롤링에 대한 의미 역시 사라집니다.

* 그리하여 (BE -> FE,   FE 에서 추출)이 아닌 (BE 에서 추출  -> FE)로 구현 방향을 잡아 FE의 컴포넌트 등의 Overhead를 최소화 시키고 FE, BE로 나누어 프로젝트를 진행하는 의미도 살릴 수 있게 됩니다.

방법:

1. FE에서 BE로 request를 보낼 때 액션 리듀서를 사용하는데 Login 같은 경우는 FE Sign in 컴포넌트에서 username 과 password라는 인자를 같이 보내 BE에서 해당 계정이 존재하는지 확인을 합니다. 

2. (1)의 동작 원리를 이용하여 BE 서버에 FE SearchTag에서 선택된 태그들을 종합하여 인자로 바꾸어주어 Rest API를 통해 BE로 보내줍니다.

3. 태그 인자들을 받은 BE는 DB의 쿼리문을 통해 해당 인자들과 관련된 데이터를 추출하여 JSON Response로 FE에 전달하게 됩니다.

4. 이렇게 되면 FE에선 각각 다른 카테고리마다 출력 Form을 설정할 필요가 없게 되고, FE 코드는 간결해지면서 BE의 역할을 의미있게 수행하는 구현이 가능해집니다.

5.  특정 인자에 대한 데이터를 가져오는 url은 /../../{attributeName}='xxx'의 식으로 규칙을 정할 예정입니다.  예를 들어, Category 는 립글로스, Color는 Red를 선택했다면 axios.get으로 호출하는 url이 /lips/category=gloss&color=red& 가 되는 것입니다.  BE에선 전달받은 인자를 파싱하여 쿼리문을 될리게 되고 추출된 데이터를 restFramework를 통해 FE로 전달하게 됩니다.

@das425 
@lllY2Klll 
@aeri206

**Comment by aeri206** [comment]
Done #82
